"""Abstract base reporter for Sentinal-Fuzz.

All report generators (JSON, HTML, SARIF, CSV) extend ``BaseReporter``
and implement the ``generate()`` method.

Usage::

    class JsonReporter(BaseReporter):
        def generate(self, result: ScanResult) -> str:
            ...

    reporter = JsonReporter(output_dir="reports")
    filepath = reporter.generate(scan_result)
"""

from __future__ import annotations

import abc
import os
from dataclasses import dataclass
from datetime import datetime
from typing import TYPE_CHECKING

from sentinal_fuzz.utils.logger import get_logger

if TYPE_CHECKING:
    from sentinal_fuzz.core.models import ScanResult

log = get_logger("reporter")


@dataclass
class BaseReporter(abc.ABC):
    """Abstract base class for all report generators.

    Subclasses must implement:
        - ``generate(scan_result) -> str``: Produce a report and return
          the file path where it was saved.

    Optionally override:
        - ``file_extension``: The default file extension for this reporter.
        - ``format_name``: Human-readable name of the format.

    Attributes:
        output_dir: Directory where report files are written.
    """

    output_dir: str = "reports"

    @property
    def file_extension(self) -> str:
        """File extension for reports generated by this reporter.

        Override in subclasses. Default: ".txt"
        """
        return ".txt"

    @property
    def format_name(self) -> str:
        """Human-readable name of this report format.

        Override in subclasses. Default: "Text"
        """
        return "Text"

    @abc.abstractmethod
    def generate(self, result: ScanResult) -> str:
        """Generate a report from scan results.

        Implementations should:
        1. Transform ``ScanResult`` into the target format
        2. Write the report to ``self.output_dir``
        3. Return the absolute file path of the generated report

        Args:
            result: The complete scan result to report on.

        Returns:
            Absolute file path of the generated report.
        """
        ...

    def _ensure_output_dir(self) -> None:
        """Create the output directory if it doesn't exist."""
        os.makedirs(self.output_dir, exist_ok=True)

    def _build_filename(self, result: ScanResult) -> str:
        """Build a descriptive filename for the report.

        Format: ``sentinal-fuzz_<target-domain>_<timestamp><extension>``

        Args:
            result: Scan result to derive the filename from.

        Returns:
            The filename string (without directory path).
        """
        from urllib.parse import urlparse

        domain = urlparse(result.target).netloc.replace(":", "_")
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        return f"sentinal-fuzz_{domain}_{timestamp}{self.file_extension}"

    def _write_file(self, filename: str, content: str) -> str:
        """Write content to a file in the output directory.

        Args:
            filename: The filename to write.
            content:  The file content string.

        Returns:
            Absolute file path of the written file.
        """
        self._ensure_output_dir()
        filepath = os.path.join(self.output_dir, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(content)
        log.info("Report saved: %s", filepath)
        return os.path.abspath(filepath)
