"""False-positive filter for Sentinal-Fuzz findings.

Implements a multi-rule filter that rejects findings likely to be
false positives by comparing the fuzzed response against the baseline.

Each rule returns ``True`` to **keep** the finding or ``False`` to
**reject** it. A finding must pass ALL rules to survive.

Usage::

    from sentinal_fuzz.fuzzer.false_positive_filter import FalsePositiveFilter

    fpf = FalsePositiveFilter()
    if fpf.should_keep(finding, baseline, fuzzed_response):
        confirmed_findings.append(finding)
"""

from __future__ import annotations

import re
from html.parser import HTMLParser
from typing import TYPE_CHECKING

from sentinal_fuzz.utils.logger import get_logger

if TYPE_CHECKING:
    from sentinal_fuzz.core.models import Finding
    from sentinal_fuzz.utils.http import Response

log = get_logger("fp_filter")


class FalsePositiveFilter:
    """Multi-rule false-positive filter.

    Rules are applied in order.  The first rule that returns ``False``
    rejects the finding immediately.
    """

    def should_keep(
        self,
        finding: Finding,
        baseline: Response,
        fuzzed: Response,
    ) -> bool:
        """Apply all FP rules and return True if the finding should be kept.

        Args:
            finding:  The candidate finding.
            baseline: The clean (no-payload) response for the same endpoint.
            fuzzed:   The response generated by the injected payload.

        Returns:
            ``True`` if the finding appears genuine; ``False`` if likely FP.
        """
        # Rule 1: Pattern already present in baseline → FP
        if not self._rule_baseline_exclusion(finding, baseline, fuzzed):
            log.debug(
                "FP rejected (baseline match): %s on %s param=%s",
                finding.template_id, finding.url, finding.parameter,
            )
            return False

        # Rule 2: Identical status + near-identical body → FP
        if not self._rule_response_differential(baseline, fuzzed):
            log.debug(
                "FP rejected (no differential): %s on %s param=%s",
                finding.template_id, finding.url, finding.parameter,
            )
            return False

        # Rule 3: XSS reflection must be unescaped
        if not self._rule_xss_unescaped(finding, fuzzed):
            log.debug(
                "FP rejected (XSS escaped): %s on %s param=%s",
                finding.template_id, finding.url, finding.parameter,
            )
            return False

        # Rule 4: Timing threshold must be significant
        if not self._rule_timing_significance(finding, baseline, fuzzed):
            log.debug(
                "FP rejected (timing insignificant): %s on %s param=%s",
                finding.template_id, finding.url, finding.parameter,
            )
            return False

        return True

    # ── Rule implementations ───────────────────────────────────────

    @staticmethod
    def _rule_baseline_exclusion(
        finding: Finding,
        baseline: Response,
        fuzzed: Response,
    ) -> bool:
        """Reject if every matched pattern already exists in baseline.

        If a server always shows "syntax error" in its footer, a regex
        match on that phrase in the fuzzed response is NOT evidence of
        SQL injection.

        Returns True to keep, False to reject.
        """
        evidence = finding.evidence
        if not evidence:
            return True   # No evidence string → can't check, keep it

        baseline_text = baseline.text.lower()

        # Parse evidence parts (format: "regex match: xxx" or "word match: …xxx…")
        # Check if the raw evidence snippets appear in the baseline too
        evidence_parts = evidence.split(" | ")
        all_in_baseline = True

        for part in evidence_parts:
            # Extract the actual matched content
            if part.startswith("word match:"):
                matched_text = part[len("word match:"):].strip().strip("…").strip()
            elif part.startswith("regex match:"):
                matched_text = part[len("regex match:"):].strip()
            elif part.startswith("status=") or part.startswith("elapsed="):
                # Status/timing are NOT content patterns — skip this rule for them
                all_in_baseline = False
                break
            elif part.startswith("header "):
                # Header checks are structural, not content
                all_in_baseline = False
                break
            else:
                matched_text = part.strip()

            if matched_text and matched_text.lower() not in baseline_text:
                all_in_baseline = False
                break

        if all_in_baseline and evidence_parts:
            return False  # All evidence was already in baseline → reject

        return True

    @staticmethod
    def _rule_response_differential(
        baseline: Response,
        fuzzed: Response,
    ) -> bool:
        """Reject if the fuzzed response is nearly identical to baseline.

        If status code is the same AND body differs by fewer than 50 bytes,
        the payload likely had no effect → false positive.

        Returns True to keep, False to reject.
        """
        if baseline.status_code != fuzzed.status_code:
            return True  # Different status → something happened

        body_diff = abs(len(fuzzed.text) - len(baseline.text))
        if body_diff < 50 and fuzzed.text.strip() == baseline.text.strip():
            return False  # Nearly identical → reject

        return True

    @staticmethod
    def _rule_xss_unescaped(
        finding: Finding,
        fuzzed: Response,
    ) -> bool:
        """Reject XSS findings where the payload is HTML-escaped.

        Only applies to XSS template IDs. Checks that the injected
        payload appears in the response WITHOUT HTML entity encoding.

        Returns True to keep, False to reject.
        """
        # Only apply to XSS-related templates
        if not _is_xss_template(finding.template_id):
            return True

        payload = finding.payload
        if not payload:
            return True

        body = fuzzed.text

        # If the raw payload is in the body → potentially real XSS
        if payload in body:
            # Additional check: make sure it's not inside an HTML comment
            # or inside a safely-quoted attribute
            if _is_in_html_comment(body, payload):
                return False
            return True

        # If the HTML-escaped version is in the body → safely escaped, not XSS
        escaped_payload = (
            payload
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
            .replace("'", "&#x27;")
        )
        if escaped_payload in body:
            return False  # Escaped → safe → reject

        # Payload not found at all (in any form) → edge case, keep for review
        return True

    @staticmethod
    def _rule_timing_significance(
        finding: Finding,
        baseline: Response,
        fuzzed: Response,
    ) -> bool:
        """Reject timing-based findings where delay is not significant.

        For time-based checks, the fuzzed response time must be at least
        2x the baseline time to be considered genuine.

        Returns True to keep, False to reject.
        """
        # Only apply to time-based templates
        if "time" not in finding.template_id and "timing" not in finding.template_id:
            return True

        baseline_ms = baseline.elapsed_ms
        fuzzed_ms = fuzzed.elapsed_ms

        # Fuzzed time must be at least 2x baseline
        if baseline_ms > 0 and fuzzed_ms < (baseline_ms * 2):
            return False

        return True


# ── Helper functions ───────────────────────────────────────────────


def _is_xss_template(template_id: str) -> bool:
    """Check if a template ID is XSS-related."""
    xss_keywords = {"xss", "cross-site", "script"}
    template_lower = template_id.lower()
    return any(kw in template_lower for kw in xss_keywords)


def _is_in_html_comment(html: str, text: str) -> bool:
    """Check if text only appears inside HTML comments."""
    # Remove all HTML comments
    no_comments = re.sub(r"<!--.*?-->", "", html, flags=re.DOTALL)
    # If the text is gone after removing comments, it was only in comments
    return text in html and text not in no_comments


def verify_xss_unescaped(response_html: str, nonce: str) -> bool:
    """Verify that a nonce appears inside an actual <script> tag in the DOM.

    Uses Python's built-in HTML parser to walk the DOM and check that
    the nonce is inside a real ``<script>`` element — not in a comment,
    not in an escaped attribute, not entity-encoded.

    Args:
        response_html: The full HTML response body.
        nonce:         The unique canary string we injected (e.g. ``sf_abc12345``).

    Returns:
        ``True`` if the nonce appears inside a real ``<script>`` tag.
    """
    parser = _XSSVerifierParser(nonce)
    try:
        parser.feed(response_html)
    except _FoundInScript:
        return True
    return False


class _FoundInScript(Exception):
    """Sentinel exception raised when nonce is found in a <script> tag."""


class _XSSVerifierParser(HTMLParser):
    """HTML parser that checks if a nonce appears in a <script> element."""

    def __init__(self, nonce: str) -> None:
        super().__init__()
        self.nonce = nonce
        self._in_script = False

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        if tag.lower() == "script":
            self._in_script = True
            # Also check the attributes (e.g. onerror, onload carry JS too)
        # Check event handler attributes for the nonce
        for attr_name, attr_value in attrs:
            if attr_value and self.nonce in attr_value:
                if attr_name.lower().startswith("on"):
                    raise _FoundInScript()

    def handle_endtag(self, tag: str) -> None:
        if tag.lower() == "script":
            self._in_script = False

    def handle_data(self, data: str) -> None:
        if self._in_script and self.nonce in data:
            raise _FoundInScript()
